REM `venv1\Scripts\activate.bat` must be run first before running the script
@echo on
python main.py "DD Lost Mine of Phandelver" "LMoP"
python main.py "DD Hoard of the Dragon Queen" "HotDQ"
python main.py "DD The Rise of Tiamat" "RoT"
python main.py "DD Princes of the Apocalypse" "PotA"
python main.py "D&D Out of the Abyss" "OotA"
python main.py "DD Curse of Strahd" "CoS"
python main.py "DD Storm King's Thunder" "SKT"
python main.py "DD TYP Against the Giants" "TftYP" "AtG"
python main.py "DD TYP Dead in Thay" "TftYP" "DiT"
python main.py "DD TYP The Forge of Fury" "TftYP" "TFoF"
python main.py "DD TYP The Hidden Shrine of Tamoachan" "TftYP" "THSoT"
python main.py "DD TYP The Sunless Citadel" "TftYP" "TSC"
python main.py "DD TYP Tomb of Horrors" "TftYP" "ToH"
python main.py "DD TYP White Plume Mountain" "TftYP" "WPM"
python main.py "DD Tomb of Annihilation" "ToA"
